// <auto-generated />
using Aula10_Avaliacao_G1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Aula10AvaliacaoG1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181005231908_Sprint01ConsultaPacientesPorPlanos")]
    partial class Sprint01ConsultaPacientesPorPlanos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Aula10_Avaliacao_G1.Models.Consulta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataHora");

                    b.Property<DateTime?>("dataRevisao");

                    b.Property<string>("oQueFoiFeito");

                    b.Property<string>("oQueFoiFeitoRevisao");

                    b.Property<int?>("pacienteid");

                    b.Property<decimal>("valorConsulta");

                    b.HasKey("id");

                    b.HasIndex("pacienteid");

                    b.ToTable("consultas");
                });

            modelBuilder.Entity("Aula10_Avaliacao_G1.Models.Paciente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataNascimento");

                    b.Property<string>("email");

                    b.Property<string>("endereco");

                    b.Property<string>("fone");

                    b.Property<string>("nome");

                    b.Property<int?>("planoid");

                    b.HasKey("id");

                    b.HasIndex("planoid");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("Aula10_Avaliacao_G1.Models.Plano", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("planos");
                });

            modelBuilder.Entity("Aula10_Avaliacao_G1.Models.Consulta", b =>
                {
                    b.HasOne("Aula10_Avaliacao_G1.Models.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("pacienteid");
                });

            modelBuilder.Entity("Aula10_Avaliacao_G1.Models.Paciente", b =>
                {
                    b.HasOne("Aula10_Avaliacao_G1.Models.Plano", "plano")
                        .WithMany()
                        .HasForeignKey("planoid");
                });
#pragma warning restore 612, 618
        }
    }
}
